import os
import pandas as pd
import re
import nltk

keywords = ['polymer',
 'acrylic acid',
 'cross-polymer',
 'monomer',
 'polymeric acrylates',
 'polymer-cross polymer',
 'vulcanisation',
 'hydrogenated polymer',
 'monomeric units',
 'polymeric units',
 'crosslinked',
 'cross chained',
 'toxicology',
 'tox',
 'non-clinical safety',
 'pre-clinical safety',
 'pre-clinical',
 'non-clinical',
 'repeat-dose toxicity',
 '90 days',
 '28 days',
 'sub acute toxicity',
 'sub chronic toxicity',
 'chronic toxicity',
 'acute oral',
 'acute dermal',
 'acute intramuscular',
 'acute intravenous',
 'acute inhalation',
 'acute intraperitoneal',
 'ld50',
 'lc50',
 'fertility',
 'reproduction',
 'reproductive toxicity',
 'organogenesis',
 'developmental toxicity',
 'teratogenic',
 'teratogenicity',
 'malformation',
 'prenatal',
 'postnatal',
 'mutation',
 'mutagen',
 'mutagenic',
 'mutagen',
 'mutagenic',
 'genotoxic',
 'genotoxicity',
 'clastogenicity',
 'clastogen',
 'chromosome aberration',
 'sister chromatid exchange',
 'dominant lethal micronucleus',
 'comet',
 'genemutation',
 'hprt',
 'xprt',
 'cell transformation',
 'unscheduled dna synthesis',
 'dna damage',
 'transgenic rodent mutation assay',
 'spermatogonial chromosome aberration',
 'mouse heritable translocation assay',
 'mouse spot test',
 'tumor',
 'neoplasm',
 'neoplastic',
 'cancer',
 'carcinogen',
 'carcinogenic',
 'carcinogenicity',
 'oncogenic',
 'oncogenicity',
 'phototoxicity',
 '3t3 neutral red uptake',
 'photosensitisation',
 'photoirritation',
 'photomutagen',
 'irritation',
 'draize',
 'reconstructed human cornea',
 'bovine corneal opacity',
 'isolated chicken eye',
 'fluorescein leakage',
 'isolated rabbit eye',
 'primary irritation index',
 'transcutaneous electrical resistance',
 'reconstructed human epidermis',
 'membrane barrier test',
 'episkin',
 'epiderm',
 'skin ethic',
 'corrosion',
 'dermal damage',
 'dermal burn',
 'peeling',
 'etching',
 'dermis',
 'dermal',
 'epidermis',
 'epidermal',
 'sub-cutaneous',
 'percutaneous',
 'skin sensitisation',
 'direct peptide reactivity assay',
 'dpra',
 'are-nrf2 luciferase test',
 'local lymph node assay',
 'guinea pig maximisation',
 'gpmt',
 'mouse ear swelling test',
 'buehler test',
 "freund's complete adjuvant test",
 'open epicutaneous test',
 'Absorption',
 'distribution',
 'biotransformation',
 'metabolism',
 'excretion',
 'pharmacokinetic',
 'toxicokinetic',
 'bioavailability',
 'mass balance study',
 'tissue distribution',
 'skin absorption',
 'dermal absorption',
 'percutaneous absorption',
 'pharmacokinetics',
 'systemic absorption',
 'dosage',
 'oral',
 'dermal',
 'intramuscular',
 'intravenous',
 'inhalation',
 'intraperitoneal',
 'ld50',
 'lc50',
 'median lethal dose',
 'sub-cutaneous',
 'iv',
 'im',
 'ip',
 'peros',
 'BD',
 'QD']
pattern_keyword = re.compile(
    '|'.join([r'\b%s\b' % keyword for keyword in keywords]),
    flags=re.IGNORECASE
)



def foo(path):

    article_filenames = filter(
        lambda filename:
            filename.startswith('article') and filename.endswith('.txt'),
        os.listdir(path)
    )

    df = pd.DataFrame(columns=['article_name', 'article_date', 'phrase', 'category', 'keyword'])
    for filename in article_filenames:
        with open(f'{path}/{filename}', encoding='utf-8') as file:
            text = file.read().replace('\n', '')
            sentences = nltk.sent_tokenize(text)
            for sentence in sentences:
                if pattern_keyword.match(sentence) is not None:
                    print(sentence)
                    print(60 * '=')
        print()


foo('/Users/gustavo/text-mining/pdf/PubMed/[\'benzyl\']')
